This notebook introduces to basic fastf1 objects like 'session', 'event', 'laps'

# Importing needed modules
Fastf1 is built mainly around pandas dataframes and series objects.

In [1]:
import fastf1
import matplotlib.pyplot as plt

In [2]:
fastf1.Cache.enable_cache(r'C:\Users\harsh\jupyter\f1_data_analysis\cache')

# Loading a session and an event
Session is the important starting point for everything in fastf1.

In [3]:
session = fastf1.get_session(2023, "Bahrain", "Q")

utils          INFO 	NumExpr defaulting to 8 threads.

In [4]:
print("session:",session.name)
print("date:",session.date)

session: Qualifying
date: 2023-03-04 18:00:00

Event object holds all the information about the session.
Event object is a pandas series.

In [5]:
session.event

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023
EventDate                                   2023-03-05 20:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                                2023-03-03 14:30:00
Session2                                             Practice 2
Session2Date                                2023-03-03 18:00:00
Session3                                             Practice 3
Session3Date                                2023-03-04 14:30:00
Session4                                             Qualifying
Session4Date                                2023-03-04 18:00:00
Session5                                                   Race
Session5Date                                2023-03-05 18:00:00
F1ApiSupport                                               True
Name: Bahrain Grand Prix, dtype: object

Event object can be loaded directly using 'get_event' method.
<br>Event can be loaded using round number, event name, country, location.
<br>Approximate match will be loaded, so better check the results before proceeding.

In [6]:
event=fastf1.get_event(2023,1)
event

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023
EventDate                                   2023-03-05 20:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                                2023-03-03 14:30:00
Session2                                             Practice 2
Session2Date                                2023-03-03 18:00:00
Session3                                             Practice 3
Session3Date                                2023-03-04 14:30:00
Session4                                             Qualifying
Session4Date                                2023-03-04 18:00:00
Session5                                                   Race
Session5Date                                2023-03-05 18:00:00
F1ApiSupport                                               True
Name: Bahrain Grand Prix, dtype: object

# loading schedule
schedule for the entire season can be loaded using 'get_event_schedule' method.

In [7]:
schedule = fastf1.get_event_schedule(2023)
schedule.head()

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session2,Session2Date,Session3,Session3Date,Session4,Session4Date,Session5,Session5Date,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2023,2023-02-25 19:30:00,Pre-Season Testing,testing,Practice 1,2023-02-23 10:00:00,Practice 2,2023-02-24 10:00:00,Practice 3,2023-02-25 10:00:00,None,NaT,None,NaT,True
1,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023,2023-03-05 20:00:00,Bahrain Grand Prix,conventional,Practice 1,2023-03-03 14:30:00,Practice 2,2023-03-03 18:00:00,Practice 3,2023-03-04 14:30:00,Qualifying,2023-03-04 18:00:00,Race,2023-03-05 18:00:00,True
2,2,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2023,2023-03-19 22:00:00,Saudi Arabian Grand Prix,conventional,Practice 1,2023-03-17 16:30:00,Practice 2,2023-03-17 20:00:00,Practice 3,2023-03-18 16:30:00,Qualifying,2023-03-18 20:00:00,Race,2023-03-19 20:00:00,True
3,3,Australia,Melbourne,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2023,2023-04-02 17:00:00,Australian Grand Prix,conventional,Practice 1,2023-03-31 12:30:00,Practice 2,2023-03-31 16:00:00,Practice 3,2023-04-01 12:30:00,Qualifying,2023-04-01 16:00:00,Race,2023-04-02 15:00:00,True
4,4,Azerbaijan,Baku,FORMULA 1 AZERBAIJAN GRAND PRIX 2023,2023-04-30 17:00:00,Azerbaijan Grand Prix,sprint_shootout,Practice 1,2023-04-28 13:30:00,Qualifying,2023-04-28 17:00:00,Sprint Shootout,2023-04-29 12:30:00,Sprint,2023-04-29 17:30:00,Race,2023-04-30 15:00:00,True

# Driver info and results
It is necessary to load the session first, this will load the data from the session for various APIs to use. 
<br>Session can be loaded using 'session.load' method

In [8]:
session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v2.3.0]
api            INFO 	Using cached data for driver_info
api            INFO 	Using cached data for timing_data
api            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
api            INFO 	Using cached data for session_status_data
api            INFO 	Using cached data for track_status_data
api            INFO 	Using cached data for car_data
api            INFO 	Using cached data for position_data
api            INFO 	Using cached data for weather_data
api            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']

In [9]:
session.results

,DriverNumber,BroadcastName,Abbreviation,TeamName,TeamColor,FirstName,LastName,FullName,Position,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,Max Verstappen,1.0,0.0,0 days 00:01:31.295000,0 days 00:01:30.503000,0 days 00:01:29.708000,NaT,,0.0
11,11,S PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,Sergio Perez,2.0,0.0,0 days 00:01:31.479000,0 days 00:01:30.746000,0 days 00:01:29.846000,NaT,,0.0
16,16,C LECLERC,LEC,Ferrari,F91536,Charles,Leclerc,Charles Leclerc,3.0,0.0,0 days 00:01:31.094000,0 days 00:01:30.282000,0 days 00:01:30,NaT,,0.0
55,55,C SAINZ,SAI,Ferrari,F91536,Carlos,Sainz,Carlos Sainz,4.0,0.0,0 days 00:01:30.993000,0 days 00:01:30.515000,0 days 00:01:30.154000,NaT,,0.0
14,14,F ALONSO,ALO,Aston Martin,358C75,Fernando,Alonso,Fernando Alonso,5.0,0.0,0 days 00:01:31.158000,0 days 00:01:30.645000,0 days 00:01:30.336000,NaT,,0.0
63,63,G RUSSELL,RUS,Mercedes,6CD3BF,George,Russell,George Russell,6.0,0.0,0 days 00:01:31.057000,0 days 00:01:30.507000,0 days 00:01:30.340000,NaT,,0.0
44,44,L HAMILTON,HAM,Mercedes,6CD3BF,Lewis,Hamilton,Lewis Hamilton,7.0,0.0,0 days 00:01:31.543000,0 days 00:01:30.513000,0 days 00:01:30.384000,NaT,,0.0
18,18,L STROLL,STR,Aston Martin,358C75,Lance,Stroll,Lance Stroll,8.0,0.0,0 days 00:01:31.184000,0 days 00:01:31.127000,0 days 00:01:30.836000,NaT,,0.0
31,31,E OCON,OCO,Alpine,2293D1,Esteban,Ocon,Esteban Ocon,9.0,0.0,0 days 00:01:31.508000,0 days 00:01:30.914000,0 days 00:01:30.984000,NaT,,0.0
27,27,N HULKENBERG,HUL,Haas F1 Team,B6BABD,Nico,Hulkenberg,Nico Hulkenberg,10.0,0.0,0 days 00:01:31.204000,0 days 00:01:30.809000,NaT,NaT,,0.0
4,4,L NORRIS,NOR,McLaren,F58020,Lando,Norris,Lando Norris,11.0,0.0,0 days 00:01:31.652000,0 days 00:01:31.381000,NaT,NaT,,0.0
77,77,V BOTTAS,BOT,Alfa Romeo,C92D4B,Valtteri,Bottas,Valtteri Bottas,12.0,0.0,0 days 00:01:31.504000,0 days 00:01:31.443000,NaT,NaT,,0.0
24,24,G ZHOU,ZHO,Alfa Romeo,C92D4B,Guanyu,Zhou,Guanyu Zhou,13.0,0.0,0 days 00:01:31.615000,0 days 00:01:31.473000,NaT,NaT,,0.0
22,22,Y TSUNODA,TSU,AlphaTauri,5E8FAA,Yuki,Tsunoda,Yuki Tsunoda,14.0,0.0,0 days 00:01:31.400000,0 days 00:01:32.510000,NaT,NaT,,0.0
23,23,A ALBON,ALB,Williams,37BEDD,Alexander,Albon,Alexander Albon,15.0,0.0,0 days 00:01:31.461000,NaT,NaT,NaT,,0.0
2,2,L SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,Logan Sargeant,16.0,0.0,0 days 00:01:31.652000,NaT,NaT,NaT,,0.0
20,20,K MAGNUSSEN,MAG,Haas F1 Team,B6BABD,Kevin,Magnussen,Kevin Magnussen,17.0,0.0,0 days 00:01:31.892000,NaT,NaT,NaT,,0.0
81,81,O PIASTRI,PIA,McLaren,F58020,Oscar,Piastri,Oscar Piastri,18.0,0.0,0 days 00:01:32.101000,NaT,NaT,NaT,,0.0
21,21,N DE VRIES,DEV,AlphaTauri,5E8FAA,Nyck,De Vries,Nyck De Vries,19.0,0.0,0 days 00:01:32.121000,NaT,NaT,NaT,,0.0
10,10,P GASLY,GAS,Alpine,2293D1,Pierre,Gasly,Pierre Gasly,20.0,0.0,0 days 00:01:32.181000,NaT,NaT,NaT,,0.0

# Working with laps and lap times
All individual laps can be accessed using 'session.laps'

In [10]:
session.laps

,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0 days 00:27:20.459000,1,NaT,1,0 days 00:18:59.843000,0 days 00:21:06.934000,NaT,NaT,NaT,NaT,...,SOFT,1.0,True,1,0 days 00:18:59.843000,Red Bull Racing,VER,5,False,2023-03-04 15:04:00.840
1,0 days 00:29:32.394000,1,NaT,2,0 days 00:27:20.459000,NaT,NaT,0 days 00:00:53.666000,0 days 00:00:38.509000,NaT,...,SOFT,2.0,False,2,0 days 00:27:20.459000,Red Bull Racing,VER,1,False,2023-03-04 15:12:21.456
2,0 days 00:31:03.689000,1,0 days 00:01:31.295000,3,NaT,NaT,0 days 00:00:29.152000,0 days 00:00:39.195000,0 days 00:00:22.948000,0 days 00:30:01.546000,...,SOFT,3.0,False,2,0 days 00:29:32.394000,Red Bull Racing,VER,1,True,2023-03-04 15:14:33.391
3,0 days 00:32:53.501000,1,0 days 00:01:49.812000,4,NaT,0 days 00:32:51.749000,0 days 00:00:35.615000,0 days 00:00:44.953000,0 days 00:00:29.244000,0 days 00:31:39.304000,...,SOFT,4.0,False,2,0 days 00:31:03.689000,Red Bull Racing,VER,1,False,2023-03-04 15:16:04.686
4,0 days 00:40:05.688000,1,NaT,5,0 days 00:37:48.525000,NaT,NaT,0 days 00:00:53.390000,0 days 00:00:45.107000,NaT,...,SOFT,1.0,True,3,0 days 00:32:53.501000,Red Bull Racing,VER,1,False,2023-03-04 15:17:54.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,0 days 00:32:13.869000,10,0 days 00:01:32.181000,2,NaT,NaT,0 days 00:00:29.330000,0 days 00:00:39.764000,0 days 00:00:23.087000,0 days 00:31:11.018000,...,SOFT,2.0,True,1,0 days 00:30:41.688000,Alpine,GAS,1,True,2023-03-04 15:15:42.685
250,0 days 00:34:06.375000,10,0 days 00:01:52.506000,3,NaT,0 days 00:34:03.170000,0 days 00:00:33.458000,0 days 00:00:47.084000,0 days 00:00:31.964000,0 days 00:32:47.327000,...,SOFT,3.0,True,1,0 days 00:32:13.869000,Alpine,GAS,1,False,2023-03-04 15:17:14.866
251,0 days 00:39:15.464000,10,NaT,4,0 days 00:36:54.776000,NaT,NaT,0 days 00:00:54.291000,0 days 00:00:45.228000,NaT,...,SOFT,1.0,True,2,0 days 00:34:06.375000,Alpine,GAS,1,False,2023-03-04 15:19:07.372
252,0 days 00:40:47.282000,10,0 days 00:01:31.818000,5,NaT,NaT,0 days 00:00:29.247000,0 days 00:00:39.412000,0 days 00:00:23.159000,0 days 00:39:44.711000,...,SOFT,2.0,True,2,0 days 00:39:15.464000,Alpine,GAS,1,True,2023-03-04 15:24:16.461
253,0 days 00:42:41.848000,10,0 days 00:01:54.566000,6,NaT,0 days 00:42:40.036000,0 days 00:00:36.951000,0 days 00:00:45.775000,0 days 00:00:31.840000,0 days 00:41:24.233000,...,SOFT,3.0,True,2,0 days 00:40:47.282000,Alpine,GAS,1,False,2023-03-04 15:25:48.279

In [11]:
session.laps.columns

Index(['Time', 'DriverNumber', 'LapTime', 'LapNumber', 'PitOutTime',
       'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Stint', 'LapStartTime', 'Team',
       'Driver', 'TrackStatus', 'IsAccurate', 'LapStartDate'],
      dtype='object')

In [12]:
fastest_lap = session.laps.pick_fastest()
print("fastest lap time:",fastest_lap['LapTime'])
print("fastest driver:",fastest_lap['Driver'])

fastest lap time: 0 days 00:01:29.708000
fastest driver: VER